name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on:
      - ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install Packages
      run: pip install -r requirements.txt

    - name: LLM
      run: FAST=true python llm.py
